using System;

namespace CSF_Operators_Div
{
    class Program
    {
        static void Main(string[] args)
        {
            var line1 = Console.ReadLine().Split(' ');
            var a = sbyte.Parse(line1[0]);

            var line2 = Console.ReadLine().Split(' ');
            var b = short.Parse(line2[0]);

            var line3 = Console.ReadLine().Split(' ');
            var c = int.Parse(line3[0]);

            var line4 = Console.ReadLine().Split(' ');
            var d = long.Parse(line4[0]);

            var line5 = Console.ReadLine().Split(' ');
            var e = byte.Parse(line5[0]);

            var line6 = Console.ReadLine().Split(' ');
            var f = ushort.Parse(line6[0]);

            var line7 = Console.ReadLine().Split(' ');
            var g = uint.Parse(line7[0]);

            var line8 = Console.ReadLine().Split(' ');
            var h = ulong.Parse(line8[0]);

            var line9 = Console.ReadLine().Split(' ');
            var i = char.Parse(line9[0]);

            var line10 = Console.ReadLine().Split(' ');
            var j = float.Parse(line10[0]);

            var line11 = Console.ReadLine().Split(' ');
            var k = double.Parse(line11[0]);

            var line12 = Console.ReadLine().Split(' ');
            var l = decimal.Parse(line12[0]);

            var a_a = a / a;
            var a_b = a / b;
            var a_c = a / c;
            var a_d = a / d;
            var a_e = a / e;
            var a_f = a / f;
            var a_g = a / g;
            //var a_h = a / h;
            var a_i = a / i;
            var a_j = a / j;
            var a_k = a / k;
            var a_l = a / l;
            Console.Write(a_a);
            Console.Write(" ");
            Console.Write(a_b);
            Console.Write(" ");
            Console.Write(a_c);
            Console.Write(" ");
            Console.Write(a_d);
            Console.Write(" ");
            Console.Write(a_e);
            Console.Write(" ");
            Console.Write(a_f);
            Console.Write(" ");
            Console.Write(a_g);
            Console.Write(" ");
            //Console.Write(a_h);
            //Console.Write(" ");
            Console.Write(a_i);
            Console.Write(" ");
            Console.Write(a_j);
            Console.Write(" ");
            Console.Write(a_k);
            Console.Write(" ");
            Console.Write(a_l);
            Console.Write(" ");
            Console.WriteLine();

            var b_a = b / a;
            var b_b = b / b;
            var b_c = b / c;
            var b_d = b / d;
            var b_e = b / e;
            var b_f = b / f;
            var b_g = b / g;
            //var b_h = b / h;
            var b_i = b / i;
            var b_j = b / j;
            var b_k = b / k;
            var b_l = b / l;
            Console.Write(b_a);
            Console.Write(" ");
            Console.Write(b_b);
            Console.Write(" ");
            Console.Write(b_c);
            Console.Write(" ");
            Console.Write(b_d);
            Console.Write(" ");
            Console.Write(b_e);
            Console.Write(" ");
            Console.Write(b_f);
            Console.Write(" ");
            Console.Write(b_g);
            Console.Write(" ");
            //Console.Write(b_h);
            //Console.Write(" ");
            Console.Write(b_i);
            Console.Write(" ");
            Console.Write(b_j);
            Console.Write(" ");
            Console.Write(b_k);
            Console.Write(" ");
            Console.Write(b_l);
            Console.Write(" ");
            Console.WriteLine();

            var c_a = c / a;
            var c_b = c / b;
            var c_c = c / c;
            var c_d = c / d;
            var c_e = c / e;
            var c_f = c / f;
            var c_g = c / g;
            //var c_h = c / h;
            var c_i = c / i;
            var c_j = c / j;
            var c_k = c / k;
            var c_l = c / l;
            Console.Write(c_a);
            Console.Write(" ");
            Console.Write(c_b);
            Console.Write(" ");
            Console.Write(c_c);
            Console.Write(" ");
            Console.Write(c_d);
            Console.Write(" ");
            Console.Write(c_e);
            Console.Write(" ");
            Console.Write(c_f);
            Console.Write(" ");
            Console.Write(c_g);
            Console.Write(" ");
            //Console.Write(c_h);
            //Console.Write(" ");
            Console.Write(c_i);
            Console.Write(" ");
            Console.Write(c_j);
            Console.Write(" ");
            Console.Write(c_k);
            Console.Write(" ");
            Console.Write(c_l);
            Console.Write(" ");
            Console.WriteLine();

            var d_a = d / a;
            var d_b = d / b;
            var d_c = d / c;
            var d_d = d / d;
            var d_e = d / e;
            var d_f = d / f;
            var d_g = d / g;
            //var d_h = d / h;
            var d_i = d / i;
            var d_j = d / j;
            var d_k = d / k;
            var d_l = d / l;
            Console.Write(d_a);
            Console.Write(" ");
            Console.Write(d_b);
            Console.Write(" ");
            Console.Write(d_c);
            Console.Write(" ");
            Console.Write(d_d);
            Console.Write(" ");
            Console.Write(d_e);
            Console.Write(" ");
            Console.Write(d_f);
            Console.Write(" ");
            Console.Write(d_g);
            Console.Write(" ");
            //Console.Write(d_h);
            //Console.Write(" ");
            Console.Write(d_i);
            Console.Write(" ");
            Console.Write(d_j);
            Console.Write(" ");
            Console.Write(d_k);
            Console.Write(" ");
            Console.Write(d_l);
            Console.Write(" ");
            Console.WriteLine();

            var e_a = e / a;
            var e_b = e / b;
            var e_c = e / c;
            var e_d = e / d;
            var e_e = e / e;
            var e_f = e / f;
            var e_g = e / g;
            var e_h = e / h;
            var e_i = e / i;
            var e_j = e / j;
            var e_k = e / k;
            var e_l = e / l;
            Console.Write(e_a);
            Console.Write(" ");
            Console.Write(e_b);
            Console.Write(" ");
            Console.Write(e_c);
            Console.Write(" ");
            Console.Write(e_d);
            Console.Write(" ");
            Console.Write(e_e);
            Console.Write(" ");
            Console.Write(e_f);
            Console.Write(" ");
            Console.Write(e_g);
            Console.Write(" ");
            Console.Write(e_h);
            Console.Write(" ");
            Console.Write(e_i);
            Console.Write(" ");
            Console.Write(e_j);
            Console.Write(" ");
            Console.Write(e_k);
            Console.Write(" ");
            Console.Write(e_l);
            Console.Write(" ");
            Console.WriteLine();

            var f_a = f / a;
            var f_b = f / b;
            var f_c = f / c;
            var f_d = f / d;
            var f_e = f / e;
            var f_f = f / f;
            var f_g = f / g;
            var f_h = f / h;
            var f_i = f / i;
            var f_j = f / j;
            var f_k = f / k;
            var f_l = f / l;
            Console.Write(f_a);
            Console.Write(" ");
            Console.Write(f_b);
            Console.Write(" ");
            Console.Write(f_c);
            Console.Write(" ");
            Console.Write(f_d);
            Console.Write(" ");
            Console.Write(f_e);
            Console.Write(" ");
            Console.Write(f_f);
            Console.Write(" ");
            Console.Write(f_g);
            Console.Write(" ");
            Console.Write(f_h);
            Console.Write(" ");
            Console.Write(f_i);
            Console.Write(" ");
            Console.Write(f_j);
            Console.Write(" ");
            Console.Write(f_k);
            Console.Write(" ");
            Console.Write(f_l);
            Console.Write(" ");
            Console.WriteLine();

            var g_a = g / a;
            var g_b = g / b;
            var g_c = g / c;
            var g_d = g / d;
            var g_e = g / e;
            var g_f = g / f;
            var g_g = g / g;
            var g_h = g / h;
            var g_i = g / i;
            var g_j = g / j;
            var g_k = g / k;
            var g_l = g / l;
            Console.Write(g_a);
            Console.Write(" ");
            Console.Write(g_b);
            Console.Write(" ");
            Console.Write(g_c);
            Console.Write(" ");
            Console.Write(g_d);
            Console.Write(" ");
            Console.Write(g_e);
            Console.Write(" ");
            Console.Write(g_f);
            Console.Write(" ");
            Console.Write(g_g);
            Console.Write(" ");
            Console.Write(g_h);
            Console.Write(" ");
            Console.Write(g_i);
            Console.Write(" ");
            Console.Write(g_j);
            Console.Write(" ");
            Console.Write(g_k);
            Console.Write(" ");
            Console.Write(g_l);
            Console.Write(" ");
            Console.WriteLine();

            //var h_a = h / a;
            //var h_b = h / b;
            //var h_c = h / c;
            //var h_d = h / d;
            var h_e = h / e;
            var h_f = h / f;
            var h_g = h / g;
            var h_h = h / h;
            var h_i = h / i;
            var h_j = h / j;
            var h_k = h / k;
            var h_l = h / l;
            //Console.Write(h_a);
            //Console.Write(" ");
            //Console.Write(h_b);
            //Console.Write(" ");
            //Console.Write(h_c);
            //Console.Write(" ");
            //Console.Write(h_d);
            //Console.Write(" ");
            Console.Write(h_e);
            Console.Write(" ");
            Console.Write(h_f);
            Console.Write(" ");
            Console.Write(h_g);
            Console.Write(" ");
            Console.Write(h_h);
            Console.Write(" ");
            Console.Write(h_i);
            Console.Write(" ");
            Console.Write(h_j);
            Console.Write(" ");
            Console.Write(h_k);
            Console.Write(" ");
            Console.Write(h_l);
            Console.Write(" ");
            Console.WriteLine();

            var i_a = i / a;
            var i_b = i / b;
            var i_c = i / c;
            var i_d = i / d;
            var i_e = i / e;
            var i_f = i / f;
            var i_g = i / g;
            var i_h = i / h;
            var i_i = i / i;
            var i_j = i / j;
            var i_k = i / k;
            var i_l = i / l;
            Console.Write(i_a);
            Console.Write(" ");
            Console.Write(i_b);
            Console.Write(" ");
            Console.Write(i_c);
            Console.Write(" ");
            Console.Write(i_d);
            Console.Write(" ");
            Console.Write(i_e);
            Console.Write(" ");
            Console.Write(i_f);
            Console.Write(" ");
            Console.Write(i_g);
            Console.Write(" ");
            Console.Write(i_h);
            Console.Write(" ");
            Console.Write(i_i);
            Console.Write(" ");
            Console.Write(i_j);
            Console.Write(" ");
            Console.Write(i_k);
            Console.Write(" ");
            Console.Write(i_l);
            Console.Write(" ");
            Console.WriteLine();

            var j_a = j / a;
            var j_b = j / b;
            var j_c = j / c;
            var j_d = j / d;
            var j_e = j / e;
            var j_f = j / f;
            var j_g = j / g;
            var j_h = j / h;
            var j_i = j / i;
            var j_j = j / j;
            var j_k = j / k;
            //var j_l = j / l;
            Console.Write(j_a);
            Console.Write(" ");
            Console.Write(j_b);
            Console.Write(" ");
            Console.Write(j_c);
            Console.Write(" ");
            Console.Write(j_d);
            Console.Write(" ");
            Console.Write(j_e);
            Console.Write(" ");
            Console.Write(j_f);
            Console.Write(" ");
            Console.Write(j_g);
            Console.Write(" ");
            Console.Write(j_h);
            Console.Write(" ");
            Console.Write(j_i);
            Console.Write(" ");
            Console.Write(j_j);
            Console.Write(" ");
            Console.Write(j_k);
            Console.Write(" ");
            //Console.Write(j_l);
            //Console.Write(" ");
            Console.WriteLine();

            var k_a = k / a;
            var k_b = k / b;
            var k_c = k / c;
            var k_d = k / d;
            var k_e = k / e;
            var k_f = k / f;
            var k_g = k / g;
            var k_h = k / h;
            var k_i = k / i;
            var k_j = k / j;
            var k_k = k / k;
            //var k_l = k / l;
            Console.Write(k_a);
            Console.Write(" ");
            Console.Write(k_b);
            Console.Write(" ");
            Console.Write(k_c);
            Console.Write(" ");
            Console.Write(k_d);
            Console.Write(" ");
            Console.Write(k_e);
            Console.Write(" ");
            Console.Write(k_f);
            Console.Write(" ");
            Console.Write(k_g);
            Console.Write(" ");
            Console.Write(k_h);
            Console.Write(" ");
            Console.Write(k_i);
            Console.Write(" ");
            Console.Write(k_j);
            Console.Write(" ");
            Console.Write(k_k);
            Console.Write(" ");
            //Console.Write(k_l);
            //Console.Write(" ");
            Console.WriteLine();

            var l_a = l / a;
            var l_b = l / b;
            var l_c = l / c;
            var l_d = l / d;
            var l_e = l / e;
            var l_f = l / f;
            var l_g = l / g;
            var l_h = l / h;
            var l_i = l / i;
            //var l_j = l / j;
            //var l_k = l / k;
            var l_l = l / l;
            Console.Write(l_a);
            Console.Write(" ");
            Console.Write(l_b);
            Console.Write(" ");
            Console.Write(l_c);
            Console.Write(" ");
            Console.Write(l_d);
            Console.Write(" ");
            Console.Write(l_e);
            Console.Write(" ");
            Console.Write(l_f);
            Console.Write(" ");
            Console.Write(l_g);
            Console.Write(" ");
            Console.Write(l_h);
            Console.Write(" ");
            Console.Write(l_i);
            Console.Write(" ");
            //Console.Write(l_j);
            //Console.Write(" ");
            //Console.Write(l_k);
            //Console.Write(" ");
            Console.Write(l_l);
            Console.Write(" ");
            Console.WriteLine();
        }
    }
}