This is makeindex, version 2.15 [MiKTeX 2.9.7000 64-bit] (kpathsea + Thai support).
Scanning style file ./mgr.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file mgr.acn....done (89 entries accepted, 0 rejected).
Sorting entries....done (624 comparisons).
Generating output file mgr.acr....done (39 lines written, 0 warnings).
Output written in mgr.acr.
Transcript written in mgr.alg.
